//
// Created by Administrator on 2018-10-18.
//

#ifndef REFACTORING_COMPUTERPLAYERCAUTIOUS_H
#define REFACTORING_COMPUTERPLAYERCAUTIOUS_H


class ComputerPlayerCautious {

};


#endif //REFACTORING_COMPUTERPLAYERCAUTIOUS_H
